"""English words as a Telugu speaker actually says them.

Piper phonemises with espeak-ng, which switches to *English* phonemes when it
meets Latin script: "property" becomes /pɹˈɒpəti/. But she says ప్రాపర్టీ, with
Telugu sounds. Training on that mismatch teaches the model a wrong mapping on
roughly a third of the corpus — every code-mixed line.

So before training (and before synthesis) the English words are rewritten in
Telugu script. Sarvam's transcriber independently wrote them the same way in
408 clips, which is what these spellings were checked against.
"""

# Spellings follow her own recordings where they differ from the dictionary
# form: she says టైం, ఎమినైటీస్, వాకిన్స్.
MAP = {
    # the pitch
    "LAMPOSE": "ల్యాంపోస్", "property": "ప్రాపర్టీ", "properties": "ప్రాపర్టీస్",
    "booking": "బుకింగ్", "bookings": "బుకింగ్స్", "online": "ఆన్లైన్",
    "platform": "ప్లాట్ఫామ్", "free": "ఫ్రీ", "live": "లైవ్", "launch": "లాంచ్",
    "stay": "స్టే", "request": "రిక్వెస్ట్", "requests": "రిక్వెస్ట్స్",
    # the property
    "rooms": "రూమ్స్", "room": "రూమ్", "beds": "బెడ్స్", "bed": "బెడ్",
    "PG": "పీజీ", "hostel": "హాస్టల్", "hostels": "హాస్టల్స్", "hotel": "హోటల్",
    "hotels": "హోటల్స్", "To-Let": "టూలెట్", "sharing": "షేరింగ్",
    "AC": "ఏసీ", "non-AC": "నాన్ ఏసీ", "rent": "రెంట్", "advance": "అడ్వాన్స్",
    # people
    "customers": "కస్టమర్స్", "customer": "కస్టమర్", "brokers": "బ్రోకర్స్",
    "walk-ins": "వాకిన్స్", "students": "స్టూడెంట్స్", "owner": "ఓనర్",
    "owners": "ఓనర్స్", "professionals": "ప్రొఫెషనల్స్", "families": "ఫ్యామిలీస్",
    "team": "టీమ్", "manager": "మేనేజర్", "tenants": "టెనెంట్స్",
    # the call
    "call": "కాల్", "number": "నంబర్", "message": "మెసేజ్", "time": "టైం",
    "WhatsApp": "వాట్సాప్", "Google": "గూగుల్", "Maps": "మ్యాప్స్",
    "details": "డీటెయిల్స్", "interest": "ఇంట్రెస్ట్", "rating": "రేటింగ్",
    "reviews": "రివ్యూస్", "review": "రివ్యూ", "commission": "కమిషన్",
    "simple": "సింపుల్", "guide": "గైడ్", "confirm": "కన్ఫర్మ్",
    "Thanks": "థ్యాంక్స్", "thanks": "థ్యాంక్స్", "sorry": "సారీ",
    "ok": "ఓకే", "OK": "ఓకే", "okay": "ఓకే",
    # the app
    "app": "యాప్", "download": "డౌన్లోడ్", "link": "లింక్", "login": "లాగిన్",
    "password": "పాస్వర్డ్", "OTP": "ఓటీపీ", "profile": "ప్రొఫైల్",
    "Add": "యాడ్", "add": "యాడ్", "Property": "ప్రాపర్టీ", "Room": "రూమ్",
    "button": "బటన్", "type": "టైప్", "select": "సెలెక్ట్", "enter": "ఎంటర్",
    "area": "ఏరియా", "landmark": "ల్యాండ్మార్క్", "pincode": "పిన్కోడ్",
    "map": "మ్యాప్", "pin": "పిన్", "location": "లొకేషన్",
    "photo": "ఫోటో", "photos": "ఫోటోస్", "camera": "కెమెరా", "icon": "ఐకాన్",
    "cover": "కవర్", "upload": "అప్లోడ్", "delete": "డిలీట్",
    "amenities": "ఎమినైటీస్", "WiFi": "వైఫై", "parking": "పార్కింగ్",
    "CCTV": "సీసీటీవీ", "mess": "మెస్", "timings": "టైమింగ్స్",
    "laundry": "లాండ్రీ", "housekeeping": "హౌస్కీపింగ్", "rules": "రూల్స్",
    "Gate": "గేట్", "visitors": "విజిటర్స్", "Boys": "బాయ్స్", "girls": "గర్ల్స్",
    "Aadhaar": "ఆధార్", "verified": "వెరిఫైడ్", "badge": "బ్యాడ్జ్",
    "Verification": "వెరిఫికేషన్", "verification": "వెరిఫికేషన్",
    "Submit": "సబ్మిట్", "notification": "నోటిఫికేషన్",
    "Accept": "యాక్సెప్ట్", "accept": "యాక్సెప్ట్",
    "Reject": "రిజెక్ట్", "reject": "రిజెక్ట్", "penalty": "పెనాల్టీ",
    "Bookings": "బుకింగ్స్", "tab": "ట్యాబ్", "check-ins": "చెక్ ఇన్స్",
    "check-out": "చెక్ అవుట్", "availability": "అవైలబిలిటీ",
    "Calendar": "క్యాలెండర్", "calendar": "క్యాలెండర్", "block": "బ్లాక్",
    "Payments": "పేమెంట్స్", "payment": "పేమెంట్", "report": "రిపోర్ట్",
    "Pending": "పెండింగ్", "dues": "డ్యూస్", "bank": "బ్యాంక్",
    "account": "అకౌంట్", "UPI": "యూపీఐ", "reply": "రిప్లై",
    "dashboard": "డ్యాష్బోర్డ్", "enquiries": "ఎంక్వైరీస్",
    "appointment": "అపాయింట్మెంట్", "Settings": "సెట్టింగ్స్",
    "settings": "సెట్టింగ్స్", "language": "లాంగ్వేజ్", "English": "ఇంగ్లీష్",
    "sound": "సౌండ్", "off": "ఆఫ్", "on": "ఆన్", "access": "యాక్సెస్",
    "Help": "హెల్ప్", "doubt": "డౌట్", "onboard": "ఆన్బోర్డ్",
    "onboarding": "ఆన్బోర్డింగ్", "website": "వెబ్సైట్", "step": "స్టెప్",
    "channel": "ఛానల్", "list": "లిస్ట్", "listing": "లిస్టింగ్",
    "clear": "క్లియర్",
    "charges": "ఛార్జెస్",
    "charge": "ఛార్జ్",
    "extra": "ఎక్స్ట్రా",
    "business": "బిజినెస్",
    "try": "ట్రై",
    "monthly": "మంత్లీ",
    "single": "సింగిల్",
    "double": "డబుల్",
    "triple": "ట్రిపుల్",
    "Hyderabad": "హైదరాబాద్",
    "follow-up": "ఫాలో అప్",
    "registration": "రిజిస్ట్రేషన్",
    "direct": "డైరెక్ట్",
    "contract": "కాంట్రాక్ట్",
    "stop": "స్టాప్",
    "public": "పబ్లిక్",
    "system": "సిస్టమ్",
    "by": "బై",
    "demand": "డిమాండ్",
    "terms": "టర్మ్స్",
    "partner": "పార్ట్నర్",
    "binding": "బైండింగ్",
    "offer": "ఆఫర్",
    "service": "సర్వీస్",
    "support": "సపోర్ట్",
    "full": "ఫుల్",
    "empty": "ఎంప్టీ",
    "student": "స్టూడెంట్",
    "family": "ఫ్యామిలీ",
    "staff": "స్టాఫ్",
    "total": "టోటల్",
    "cash": "క్యాష్",
    "month": "మంత్",
    "week": "వీక్",
    "day": "డే",
    "morning": "మార్నింగ్",
    "evening": "ఈవెనింగ్",
    "night": "నైట్",
    "today": "టుడే",
    "tomorrow": "టుమారో",
    "yes": "యెస్",
    "no": "నో",
    "please": "ప్లీజ్",
    "phone": "ఫోన్",
    "mobile": "మొబైల్",
    "email": "ఈమెయిల్",
    "address": "అడ్రస్",
    "name": "నేమ్",
    "demo": "డెమో",
    "screenshot": "స్క్రీన్షాట్",
    "click": "క్లిక్",
    "quality": "క్వాలిటీ",
    "video": "వీడియో",
    "file": "ఫైల్",
    "share": "షేర్",
    "update": "అప్డేట్",
    "discount": "డిస్కౌంట్",
    "training": "ట్రైనింగ్",
    "range": "రేంజ్",
    "member": "మెంబర్",
    "connect": "కనెక్ట్",
    "line": "లైన్",
    "contact": "కాంటాక్ట్",
    "Play": "ప్లే",
    "Store": "స్టోర్",
    "complete": "కంప్లీట్",
    "Details": "డీటెయిల్స్",
    "Notification": "నోటిఫికేషన్",
    "Tenants": "టెనెంట్స్",
    "Reviews": "రివ్యూస్",
    "Dashboard": "డ్యాష్బోర్డ్",
    "Amenities": "ఎమినైటీస్",
    "Photos": "ఫోటోస్",
    "top": "టాప్",
    "form": "ఫారం",
    "fill": "ఫిల్",
    "clarity": "క్లారిటీ",
    "mention": "మెన్షన్",
    "price": "ప్రైస్",
    "Suma": "సుమా", "Sri": "శ్రీ", "Sai": "సాయి", "Kavya": "కావ్య",
}
